name: bit_pattern
description: >
  Bit sequence matchers for building emulators in Dart.
author: Kendal Harland <kendaljharland@gmail.com>
homepage: https://github.com/kharland/bit_pattern
version: 0.0.1
environment:
  sdk: '>=1.22.0 <2.0.0'
dependencies:
 binary: '^0.1.3'
 meta: '^1.0.5'
dev_dependencies:
  presubmit: '0.0.2'
  test: '^0.12.18+1'
